version: '3'

services:
  web-landing:
    build: .
    container_name: yumbrel_landing
    restart: always
    ports:
      # EL TRUCO: Mapeamos el puerto 8081 del VPS al 80 del contenedor
      - "8081:80"